version: "3.8"

services:
    pgsql_db:
        image: postgres:15-alpine
        container_name: cctv_container
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: cctv_db
            POSTGRES_USER: cctv
            POSTGRES_PASSWORD: rahasia123
        volumes:
            - cctv_pg_data:/var/lib/postgresql/data

volumes:
    cctv_pg_data:
