[phases.setup]
nixPkgs = ["..."]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction", "rm -rf node_modules", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"
